# Generated by Django 5.1 on 2024-08-23 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('interece', models.TextField()),
                ('descricao', models.TextField()),
                ('habilidades', models.TextField()),
                ('experiencia_profissional', models.TextField()),
                ('projetos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('sobre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_blog.sobre')),
            ],
        ),
    ]
